export const POKEMON_LOADING = "POKEMON_LOADING";
export const POKEMON_DATA_LOADED = "POKEMON_DATA_LOADED";
export const POKEMON_LOADING_FAILED = "POKEMON_LOADING_FAILED";
export const POKEMON_ADDED = "POKEMON_ADDED";
